### ISSUE TITLE
has_one / has_many not working as expected

### ISSUE THREAD

**Issue by inveterateliterate** [LaunchPadLab/decanter#75] opened 2019-11-20 19:25 UTC
in version 2.1.1, the `has_one` and `has_many` declarations is not picking up the nested objects with names like `children_ojects_attributes`

**Comment by francirp** [comment] 2019-11-20 20:20
What would be an example of inbound params we need to handle? Something like this?:

```
{
  users_attributes: [
   {
     first_name: 'Ifat',
   }
  ]
}
```

```
class MyDecanter
  has_many :users
end

class UserDecanter
  input :first_name
end
```

Should it also handle the key not having _attributes at the end or should we assume has_many always entails _attributes at the end like Rails does?
```
{
  users: [
   {
    first_name: 'Ifat',
   }
  ]
}
```

**Comment by inveterateliterate** [comment] 2019-11-20 20:22
hmm maybe a question for @dpikt - do we generally try to get the client to align with the rails convention for nested attributes?

Allowing it to not have `_attributes` is certainly more flexible

**Comment by dpikt** [comment] 2019-11-21 17:23
I think the answer depends on what `v1` does. Does that assume `_attributes` naming? Or would that be an enhancement?

**Comment by dpikt** [comment] 2020-01-28 17:40
Confirmed that v1 assumes `_attributes` naming - marking this as wontfix since it's a bug in v2.

**Closed by dpikt** 2020-01-28 17:40 UTC
